Mongodb
ClubCedille/trema pull request #11
Opened 2022-06-17 20:58 UTC by SonOfLope

closes #6

2022-07-20 22:04 UTC, ThomasCardin requested changes
Solide! Le review a été fait par moi, Jonathan et Davina.

2022-07-21 13:21 UTC, GRV96 commented on discord_util.py
> +		await user.send(message)
Désolé. Je ne comprends pas.

2022-09-19 17:29 UTC, SonOfLope reviewed
J'ai mit un commentaire par rapport au canal utilisé pour les instructions. J'aimerai simplement comprendre à quel moment on fait l'analyse du message pour identifier le canal.

2022-09-19 17:29 UTC, SonOfLope commented on schemas/welcome.json
> +        "instruct_chan_id": {"type": ["number", "null"]}
Où est-ce que tu fait l'analyse du message pour trouver le canal identifier par un # ?

2022-09-19 17:33 UTC, GRV96 commented on schemas/welcome.json
> +        "instruct_chan_id": {"type": ["number", "null"]}
J'implémenterai cette analyse dans une autre branche. Cette pull request est déjà assez grosse.

2022-09-19 18:06 UTC, ThomasCardin commented
LGTM!

2022-09-19 18:08 UTC, ThomasCardin approved these changes

2022-09-19 18:44 UTC, GRV96 approved these changes

2022-09-19 18:45 UTC, merged