Message d'accueil pour les nouveaux membres
ClubCedille/trema pull request #8
Opened 2022-06-08 20:13 UTC by GRV96

* Trëma publie un message de bienvenue dans le canal système à l'arrivée d'un nouveau membre.
* Quinze minutes plus tard, Trëma rappelle au nouveau membre de choisir un rôle s'il ne l'a pas fait.
* Trëma publie un message dans le canal système quand un membre quitte le serveur.

Close #2

2022-06-17 13:41 UTC, ThomasCardin requested changes
Une grande partie des messages sont "hardcoder" dans le code. Sachant que Trema va être utilisé par d'autres serveurs que le nôtre, il faut passer une commande au bot qui va remplir tous les paramètres. Voici un exemple: /memberjoin message: ... rappel: ... canal-cible: ..

2022-06-17 14:50 UTC, GRV96 commented
@ThomasCardin @SonOfLope J'ai déjà abordé ce sujet avec vous. J'ai proposé d'implémenter Trëma pour Cédille puis de le rendre adaptable à tous les clubs. Vous étiez d'accord. Je vous invite à créer une issue pour cette tâche.

2022-06-17 14:55 UTC, SonOfLope commented
J'ai resolve les changements demander par @ThomasCardin qui vont être implémenté dans une autre issue.

2022-06-17 17:00 UTC, ThomasCardin commented
Dans son ensemble c'est bien @GRV96, mais le résultat de la PR ne répond pas aux demandes de l'issue. Je me souviens t'avoir parlé du fait qu'une commande doit ressemblé à  /memberjoin message: ... rappel: ... canal-cible: ... Je vais apporter plus de détails aux issues pour qu'il n'y ait aucune ambigüité. On se reparle mercredi.

2022-06-29 20:16 UTC, ThomasCardin approved these changes

2022-06-29 20:17 UTC, SonOfLope approved these changes

2022-06-29 20:17 UTC, merged